version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=charan
      - POSTGRES_PASSWORD=Kanwaldotuniv1!
      - POSTGRES_DB=shelter3
    ports:
      - "5432:5432"
    volumes:
      - db_vol3:/var/lib/postgresql/data
      - ./scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  pipeline:
    build: .
    environment:
      - WAREHOUSE_USER=charan
      - WAREHOUSE_PASSWORD=Kanwaldotuniv1!
      - WAREHOUSE_DB=shelter3
      - WAREHOUSE_HOST=db
      - WAREHOUSE_PORT=5432
    depends_on:
      - db

volumes:
  db_vol3:

    